### ISSUE TITLE
error  cp: cannot stat 'simple.wasm': No such file or directory

### ISSUE THREAD

**Issue by eccentricexit** [mrsmkl/coindrop#1]
Following the [tutorial on the wrapper wiki](https://github.com/TrueBitFoundation/emscripten-module-wrapper/wiki/Tutorial) the following command fails:

`node ~/Tools/emscripten-module-wrapper/prepare.js ~/Projects/coindrop/simple.js --file input.data --file output.data`

output
```
/tmp/emscripten-module-wrapper2lt7m3r
[Function: exec] 'cp' [ '/home/rigel/Projects/coindrop/simple.wasm',
  '/tmp/emscripten-module-wrapper2lt7m3r//home/rigel/Projects/coindrop/simple.wasm' ] '/home/rigel/Projects/coindrop'
error  cp: cannot stat '/home/rigel/Projects/coindrop/simple.wasm': No such file or directory
 [ '/home/rigel/Projects/coindrop/simple.wasm',
  '/tmp/emscripten-module-wrapper2lt7m3r//home/rigel/Projects/coindrop/simple.wasm' ]
(node:5337) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Command failed: cp /home/rigel/Projects/coindrop/simple.wasm /tmp/emscripten-module-wrapper2lt7m3r//home/rigel/Projects/coindrop/simple.wasm
cp: cannot stat '/home/rigel/Projects/coindrop/simple.wasm': No such file or directory

(node:5337) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
It seems that the wasm file is not being generated.

**Comment by mrsmkl** [comment]
I think the problen is that you have a different version of LLVM. Added this to tutorial:
You need to have a version of LLVM with WebAssembly support, fastcomp is not currently supported. See this page for details: https://github.com/kripken/emscripten/wiki/New-WebAssembly-Backend, and https://github.com/mrsmkl/llvm6-wasm/blob/master/Dockerfile has a build script that should work (remember to update emscripten configuration).

@

**Comment by eccentricexit** [comment]
Thank you, that was it. Using the provided container worked nicely.
